apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: kwon5891/customer-service:latest
          ports:
            - containerPort: 9091