apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-one-deployment
spec:
  selector:
    matchLabels:
      app: provider-one
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: provider-one
    spec:
      containers:
        - name: provider-one
          image: kwon5891/provider_test:latest
          ports:
            - containerPort: 8080
