
server:
  port: 8089

logging:
  level:
    org.springframework: DEBUG

management:
  endpoint:
    web:
      exposure:
        include: "*"
#Actuator

#spring:
#  security:
#    user:
#      name: capstone
#      password: capstone
#Security


h2:
  console:
    enabled: true

spring:
  jpa:
    show-sql: true
#  application:
#    name : customer

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8090/eureka/